# Generated by Django 5.2.1 on 2025-05-23 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='contexto',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='hora_preferida',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('push', 'Push'), ('motivacional', 'Motivacional'), ('recordatorio', 'Recordatorio'), ('felicitacion', 'Felicitación')], default='motivacional', max_length=30),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL),
        ),
    ]
