# Generated by Django 5.2.1 on 2025-05-20 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('grupo_muscular', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('imagen_url', models.URLField(blank=True, null=True)),
                ('equipo', models.CharField(blank=True, max_length=100, null=True)),
                ('dificultad', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(default='activo', max_length=20)),
                ('creado_por_ia', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('objetivo', models.CharField(max_length=255)),
                ('status', models.CharField(default='activo', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('tipo_respuesta', models.CharField(default='texto', max_length=50)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('es_obligatoria', models.BooleanField(default=True)),
                ('activa', models.BooleanField(default=True)),
                ('editable_por_admin', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField()),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('entrenamiento', 'Entrenamiento'), ('descanso', 'Descanso')], max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeticiones', models.PositiveIntegerField()),
                ('series', models.PositiveIntegerField()),
                ('peso_sugerido', models.FloatField(blank=True, null=True)),
                ('descanso_segundos', models.PositiveIntegerField(default=60)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.exercise')),
            ],
        ),
    ]
