# Generated by Django 5.2.1 on 2025-05-23 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_userfitnessprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
