# Generated by Django 5.2.1 on 2025-05-23 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_routine_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='fecha_realizacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routine',
            name='realizada',
            field=models.BooleanField(default=False),
        ),
    ]
