# Generated by Django 5.2.1 on 2025-05-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_routine_fecha_realizacion_routine_realizada'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseroutine',
            name='status',
            field=models.CharField(default='activo', max_length=20),
        ),
        migrations.AddField(
            model_name='routine',
            name='status',
            field=models.CharField(default='activo', max_length=20),
        ),
    ]
