# Generated by Django 5.2.1 on 2025-05-20 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Progreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('peso', models.FloatField(blank=True, null=True)),
                ('medidas', models.JSONField(blank=True, null=True)),
                ('imc', models.FloatField(blank=True, null=True)),
                ('energia', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('foto_progreso', models.ImageField(blank=True, null=True, upload_to='progress_photos/')),
            ],
        ),
    ]
