# Generated by Django 5.2.1 on 2025-05-22 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_tipo_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='altura',
        ),
        migrations.RemoveField(
            model_name='user',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='user',
            name='motivacion',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nivel_actividad',
        ),
        migrations.RemoveField(
            model_name='user',
            name='objetivo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ocupacion',
        ),
        migrations.RemoveField(
            model_name='user',
            name='peso',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sexo',
        ),
    ]
