# Generated by Django 5.2.1 on 2025-05-20 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('feedback', 'Feedback'), ('sugerencia', 'Sugerencia'), ('reporte', 'Reporte')], max_length=30)),
                ('mensaje', models.TextField()),
                ('status', models.CharField(default='pendiente', max_length=20)),
            ],
        ),
    ]
